# Generated by Django 4.0.4 on 2022-05-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='Any', upload_to='myphoto'),
        ),
    ]
